name: Build and Deploy Flutter Web

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.35.2'
        channel: 'stable'
        
    - name: Install dependencies
      run: |
        cd frontend
        flutter pub get
        
    - name: Build Flutter Web (Debug - working version)
      run: |
        cd frontend
        flutter build web --debug --dart-define=API_URL=https://web-production-1e39.up.railway.app/api
        ls -la build/web/
        
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      if: github.ref == 'refs/heads/main'
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: frontend/build/web
        
    - name: Create build artifact
      uses: actions/upload-artifact@v3
      with:
        name: flutter-web-build
        path: frontend/build/web/
